name: Code Quality Check + Full Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # ---------- Python Setup ----------
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      # ---------- Node.js Setup ----------
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      # ---------- Environment Variables ----------
      - name: Set up environment variables
        run: |
          echo "GITHUB_TOKEN=${{ secrets.GH_TOKEN }}" >> .env
          echo "GEN_AI_STUDIO_API_KEY=${{ secrets.GEN_AI_STUDIO_API_KEY }}" >> .env
          echo "LOG_LEVEL=0" >> .env
          echo "LOG_FILE=log.log" >> .env
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          GEN_AI_STUDIO_API_KEY: ${{ secrets.GEN_AI_STUDIO_API_KEY }}
          LOG_LEVEL: 0
          LOG_FILE: log.log

      # ---------- Install Dependencies ----------
      - name: Install dependencies
        run: ./run install

      # ---------- flake8 Linting ----------
      - name: Run flake8 checks
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics --exit-zero
          flake8 . --count --max-complexity=10 --max-line-length=128 --statistics --exit-zero

      # ---------- Run Tests ----------
      - name: Run tests
        run: |
          echo "Environment check:"
          echo "GITHUB_TOKEN is set: $([[ -n "$GITHUB_TOKEN" ]] && echo "yes" || echo "no")"
          echo "GEN_AI_STUDIO_API_KEY is set: $([[ -n "$GEN_AI_STUDIO_API_KEY" ]] && echo "yes" || echo "no")"
          echo "LOG_FILE: $LOG_FILE"
          echo "LOG_LEVEL: $LOG_LEVEL"
          echo "Contents of .env:"
          cat .env || echo "No .env file"
          echo "Running test command..."
          ./run test
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          GEN_AI_STUDIO_API_KEY: ${{ secrets.GEN_AI_STUDIO_API_KEY }}
          LOG_LEVEL: 0
          LOG_FILE: log.log
      