# name: CI - Install, Lint, and Test

# on:
#   pull_request:
#     branches: [ main ]

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#       # Checkout repository
#       - uses: actions/checkout@v4

#       # Set up Python 3.11
#       - name: Set up Python 3.11
#         uses: actions/setup-python@v5
#         with:
#           python-version: '3.11'
#           cache: 'pip'

#       # Set up Node.js (for npm install)
#       - name: Set up Node.js
#         uses: actions/setup-node@v4
#         with:
#           node-version: '18'

#       # Make script executable
#       - name: Ensure run script is executable
#         run: chmod +x run

#       # Install dependencies
#       - name: Install dependencies
#         run: ./run install

#       # Run tests
#       - name: Run project tests
#         run: ./run test



name: Code Quality Check + Full Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # ---------- Python Setup ----------
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest pytest-cov
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      # ---------- flake8 Linting ----------
      - name: Run flake8 checks
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics --exit-zero
          flake8 . --count --max-complexity=10 --max-line-length=128 --statistics --exit-zero
      